{% set name = "llama-index" %}
{% set version = "0.14.24" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
    sha256: 9574d3dbd6ba247bd523e78771647807794cce9a47410dbc70ed337bb610a6ff
  - url: https://github.com/run-llama/{{ name.replace('-', '_') }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b80b8ab7fc37b88c715134d195e6f84d88758e0fe0eda1bc643713ea70933946
    folder: gh_src

build:
  number: 0
  # llama-index-core doesn't support Python 3.14+ because of dataclasses-json, which is unmaintainable anymore,
  # and does not support Python 3.14+ as well (https://github.com/lidatong/dataclasses-json/issues/568)
  skip: true  # [py<310 or py>313]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - llama-index-core >=0.14.22,<0.15.0
    - llama-index-embeddings-openai >=0.6.0,<0.7
    - llama-index-llms-openai >=0.7.0,<0.8
    - nltk >=3.9.3

# Integration tests are failed in Conda environment
#AssertionError: assert 'Would bump tests/data/package1 from 1.0.0 to 1.0.1' in 'Would bump gh_src/llama-dev/tests/data/package1 from 1.0.0 to 1.0.1\n'
#where 'Would bump gh_src/llama-dev/tests/data/package1 from 1.0.0 to 1.0.1\n' = <Result okay>.output
# Integration tests are failed in Conda environment
#where '' = <Result ValueError("'/fake/repo/package1' is not in the subpath of '$SRC_DIR/gh_src/llama-dev/tests/data'")>.stdout
# Integration tests are failed in Conda environment
#assert <ResultStatus.NO_TESTS: 4> == <ResultStatus.INSTALL_FAILED: 1>
#where <ResultStatus.INSTALL_FAILED: 1> = ResultStatus.INSTALL_FAILED
# Failed on CI in Conda environment

{% set tests_to_skip = "test_bump_command_specific_packages_dry_run" %}
{% set tests_to_skip = tests_to_skip + " or test_command_nothing_changed" %}
{% set tests_to_skip = tests_to_skip + " or test_coverage_failures" %}
{% set tests_to_skip = tests_to_skip + " or test_install_failures" %}
{% set tests_to_skip = tests_to_skip + " or test_skip_failures_no_tests" %}
{% set tests_to_skip = tests_to_skip + " or test_skip_failures_unsupported_python" %}
{% set tests_to_skip = tests_to_skip + " or test_success" %}
{% set tests_to_skip = tests_to_skip + " or test_install_dependencies_failure" %}
{% set tests_to_skip = tests_to_skip + " or test_install_local_packages_failure" %}
{% set tests_to_skip = tests_to_skip + " or test_pytest_failure " %}
{% set tests_to_skip = tests_to_skip + " or test_coverage_failure" %}
{% set tests_to_skip = tests_to_skip + " or test_successful_run" %}
{% set tests_to_skip = tests_to_skip + " or test_successful_run_with_coverage" %}
{% set tests_to_skip = tests_to_skip + " or test_version" %}
{% set tests_to_skip = tests_to_skip + " or test_bump_command_with_all_flag" %}
{% set tests_to_skip = tests_to_skip + " or test_bump_command_specific_packages" %}
{% set tests_to_skip = tests_to_skip + " or test_bump_command_specific_packages_not_a_package" %}
{% set tests_to_skip = tests_to_skip + " or test_cmd_exec_invalid_package" %}
{% set tests_to_skip = tests_to_skip + " or test_cmd_exec_all_flag" %}
{% set tests_to_skip = tests_to_skip + " or test_cmd_exec_single_package_success" %}
{% set tests_to_skip = tests_to_skip + " or test_cmd_exec_failure_without_fail_fast" %}
{% set tests_to_skip = tests_to_skip + " or test_cmd_exec_failure_with_fail_fast" %}
{% set tests_to_skip = tests_to_skip + " or test_cmd_exec_multiple_packages" %}
{% set tests_to_skip = tests_to_skip + " or test_cmd_exec_silent" %}
{% set tests_to_skip = tests_to_skip + " or test_info_with_package_names" %}
{% set tests_to_skip = tests_to_skip + " or test_info_with_all_flag" %}
{% set tests_to_skip = tests_to_skip + " or test_info_invalid_package" %}
{% set tests_to_skip = tests_to_skip + " or test_command_pr_fetch_failed" %}
{% set tests_to_skip = tests_to_skip + " or test_command_dry_run" %}
{% set tests_to_skip = tests_to_skip + " or test_command_success" %}
{% set tests_to_skip = tests_to_skip + " or test_get_latest_tag" %}
{% set tests_to_skip = tests_to_skip + " or test_get_pr_numbers" %}
{% set tests_to_skip = tests_to_skip + " or test_extract_pr_data" %}
{% set tests_to_skip = tests_to_skip + " or test_check_command" %}
{% set tests_to_skip = tests_to_skip + " or test__pytest" %}
{% set tests_to_skip = tests_to_skip + " or test_get_dependants_packages" %}

test:
  source_files:
    - gh_src/llama-dev/
  imports:
    - llama_index
  commands:
    - pip check
    - pytest -v -m "not (require_integration or slow or performance)" -k "not ({{ tests_to_skip }})" gh_src/llama-dev/tests/
  requires:
    - pip
    - pytest >=8.2.1
    - rich >=13.10.0,<15.0.0
    - tomli >=2.2.1,<3.0.0

about:
  home: https://www.llamaindex.ai/
  summary: Interface between LLMs and your data
  description: |
    LlamaIndex (formerly GPT Index) is a data framework for LLM applications
    to ingest, structure, and access private or domain-specific data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://developers.llamaindex.ai/python/framework/
  dev_url: https://github.com/run-llama/llama_index

extra:
  recipe-maintainers:
    - pavelzw
