{% set name = "llama-index" %}
{% set version = "0.8.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_index-{{ version }}.tar.gz
  sha256: 11774351f72a49c3312a6d5cfb901d1edfe4220d04fba5170b49658df402f935

build:
  number: 0
  # openai >=0.26.4 isn't available on s390x
  skip: true  # [s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - tiktoken
    - dataclasses-json
    - langchain >=0.0.293
    - sqlalchemy >=2.0.15
    - numpy
    - tenacity >=8.2.0,<9.0.0
    - openai >=0.26.4
    - pandas
    - urllib3 <2
    - fsspec >=2023.5.0
    - typing_inspect >=0.8.0
    - typing-extensions >=4.5.0
    - beautifulsoup4
    - nest-asyncio
    - nltk

test:
  imports:
    - llama_index
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jerryjliu/llama_index
  dev_url: https://github.com/jerryjliu/llama_index
  doc_url: https://gpt-index.readthedocs.io/
  summary: Interface between LLMs and your data
  description: |
    LlamaIndex (formerly GPT Index) is a data framework for LLM applications to ingest, structure, 
    and access private or domain-specific data.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
